#!/usr/bin/env bash
################################################
### 功能: iptables防火墙管理脚本
### 作者: Awkee
### 
#   链接: https://git.io/fwctl
#   博客: https://vlike.work
#
# IP数据源参考链接:
#   - 按省市级分类IP段: https://github.com/out0fmemory/qqwry.dat
#   - 按运营商分类IP段: https://github.com/gaoyifan/china-operator-ip
# 市级名称及编码信息: https://raw.githubusercontent.com/uiwjs/province-city-china/gh-pages/city.json
################################################

source $HOME/.bashrc

# 保存ipset数据
ipset_file=/etc/ipset_all.txt
# 保存iptables规则
iptables_file=/etc/sysconfig/iptables

########### 文字显示 ######
    ## 格式:\033[属性;文本色;背景色m
    ## Attribute codes:
    ## 00=none 01=bold 04=underscore 05=blink 07=reverse 08=concealed 
    ## Text color codes:
    ## 30=black 31=red 32=green 33=yellow 34=blue 35=magenta 36=cyan 37=Light gray
    ## 90=Dark gray 91=Light red 92...97=White
    ## Background color codes:
    ## 40=black 41=red 42=green 43=yellow 44=blue 45=magenta 46=cyan 47=white

    ## \033[0m 关闭所有属性
    ## \033[1m 设置高亮度
    ## \033[4m 下划线
    ## \033[5m 闪烁
    ## \033[7m 反显 
    ## \033[8m 消隐 
    ## \033[30m — \33[37m 设置前景色 
    ## \033[40m — \33[47m 设置背景色 
    ## \033[nA 光标上移n行 
    ## \033[nB 光标下移n行 
    ## \033[nC 光标右移n行 
    ## \033[nD 光标左移n行 
    ## \033[y;xH设置光标位置
    ## \033[2J 清屏
    ## \033[K 清除从光标到行尾的内容 
    ## \033[s 保存光标位置 
    ## \033[u 恢复光标位置 
    ## \033[?25l 隐藏光标 
    ## \033[?25h 显示光标


white() {
    printf "\033[0;97;1m $@ \033[0m"
}
red() {
    printf "\033[0;31;1m $@ \033[0m"
}
green() {
    printf "\033[0;32;7m $@ \033[0m"
}

gen_cn_ip() {
    # 生成默认的全国过IP段 ipset 白名单规则
    echo "create whitelist hash:net family inet hashsize 1024 maxelem 65536" > ${ipset_file}
    cn_url="https://bgp.space/china.html"
    curl ${cn_url} 2>/dev/null | awk '/^[1-9]/{ gsub("<br>",""); print "add whitelist "$0 }' >> ${ipset_file}
}

urlencode() {
  LC_ALL=C awk -- '
    BEGIN {
      for (i = 1; i <= 255; i++) hex[sprintf("%c", i)] = sprintf("%%%02X", i)
    }
    function urlencode(s,  c,i,r,l) {
      l = length(s)
      for (i = 1; i <= l; i++) {
        c = substr(s, i, 1)
        r = r "" (c ~ /^[:\/\-._~0-9a-zA-Z]$/ ? c : hex[c])
      }
      return r
    }
    BEGIN {
      for (i = 1; i < ARGC; i++)
        print urlencode(ARGV[i])
    }' "$@"
}




gen_city_ip() {
    # 根据输入省份或者地市名称生成 ipset 规则
    city_name="$1"
    isp_name="$2"
    base_url="https://raw.githubusercontent.com/learnhard-cn/china-ip-list/main"
    iplist_url="${base_url}/ip.list"
    tmp_file=".tmp.list"
    curl -L ${iplist_url} 2>/dev/null | grep "$city_name" > $tmp_file
    if [ ! -z "$tmp_file" ] ; then
        # 找到匹配地区IP段文件
        echo "create whitelist hash:net family inet hashsize 1024 maxelem 65536" > ${ipset_file}

        read -p "输入您的网络运营商名称[联通, 电信, 移动, 铁通, 科技网, 广电, 教育网, 方正宽带](回车选择默认:全部):" str_isp
        cat $tmp_file | while read fn
        do
            fname=`urlencode "${base_url}/${fn}"`

            # 按运营商过滤IP段
            echo "下载文件[${fn}]"
            if [ "$str_isp" != "" ] ; then
                echo "过滤ISP运营商: [$str_isp]"
                curl -L ${fname} 2>/dev/null | grep "$str_isp" | awk '{printf("add whitelist %s\n", $1);}' >> ${ipset_file}
                echo "当前ipset规则数: `wc -l ${ipset_file}`"
            else
                curl -L ${fname} 2>/dev/null | awk '{ printf("add whitelist %s\n", $1);}' >> ${ipset_file}
            fi
        done
    else
        echo "没找到您输入的地区 [$city_name]! 只能默认国内所有IP了."
        gen_cn_ip
    fi

    rm -f $tmp_file
}

firewall_init() {
    # 初始化防火墙配置规则
    echo "您当前防火墙配置情况如下:"
    iptables-save
    read -p "确定初始化防火墙规则?(回车继续,Ctrl+C取消)" str_answer
    
    iptables -F && ipset -! destroy whitelist

    echo "开始初始化ipset,添加国内IP段!"

    read -p "输入希望添加的IP段省份名称(默认:全国):" str_prov
    if [ "$str_prov" = "" -o "$str_prov" = "全国" -o "$str_prov" = "国内" ] ; then
        gen_cn_ip
    else
        # 单独省份或地市IP段
        gen_city_ip $str_prov
    fi
    ipset -! restore < ${ipset_file}
    echo "初始化ipset结束!"

    echo "开始创建iptables防火墙:"

    echo "关闭 firewalld 服务, 使用 iptables 服务"
    systemctl disable --now firewalld.serverce

    echo "安装iptables-service服务"
    yum install -y iptables-services

    echo "配置 iptables 防火墙规则:"
    # 允许服务器本机对外访问:允许内部向外发消息
    iptables -I OUTPUT -j ACCEPT
    # 接收内部地址消息
    iptables -A INPUT -s 127.0.0.1 -j ACCEPT

    # 放行已建立连接的相关数据
    iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

    # 开放端口列表示例(一次添加多个端口)
    iptables -A INPUT -p tcp -m multiport --dports 22,80,443,8080,12340:12350 -j ACCEPT

    # 白名单规则示例: 限制访问53端口(DNS服务)
    iptables -A INPUT -m set --match-set whitelist src -p udp --destination-port 53 -j ACCEPT
    iptables -A INPUT -m set --match-set whitelist src -p tcp --destination-port 53 -j ACCEPT
    iptables -A INPUT -p tcp --dport 53 -j DROP
    iptables -A INPUT -p udp --dport 53 -j DROP

    # 丢弃所有ICMP协议(不让ping)
    iptables -A FORWARD -p icmp -j DROP
    # 丢弃所有(不需要)的请求数据
    iptables -A INPUT -j DROP
    
    echo "`green 完成防火墙初始化配置`"
    # firewall_save
}

firewall_save() {
    # 导出防火墙配置规则
    echo "备份 ipset 列表"
    ipset save whitelist > $ipset_file

    # 导出iptables规则
    echo "备份 iptables 规则"
    iptables-save -f ${iptables_file}

    echo "================================================"
    echo "想要修改 ipset 和 iptables 规则，可以手工修改文件:"
    echo "ipset 规则文件: ${ipset_file}"
    echo "iptables 规则文件: ${iptables_file}"
    echo "================================================"
    echo
}

firewall_restore() {
    # 恢复防火墙配置规则
    echo "恢复 ipset 列表"
    ipset -! restore < $ipset_file

    echo "恢复 iptables 防火墙规则"
    iptables-restore $iptables_file
}

add_port() {
    port=$1
    iptables -A INPUT -m set --match-set whitelist src -p tcp --destination-port ${port} -j ACCEPT
}

del_port() {
    port=$1
    iptables -S| grep "port ${port} "| awk '{ gsub("-A", "-D"); print "iptables "$0 }' | bash
}

add_wip() {
    aip="$1"
    ipset add whitelist $aip
}

del_wip() {
    aip="$1"
    ipset del whitelist $aip
}


firewall_status() {
    echo "白名单IP列表规则:"
    ipset list whitelist
    echo "=============================="
    echo "防火墙规则:"
    iptables -S
    echo "=============================="
    netstat -tuanp|grep LISTEN
    echo "=============================="
    echo "ipset白名单文件恢复、保存路径:${ipset_file}"
    echo "iptables防火墙规则文件恢复、保存路径:${iptables_file}"
    echo "=============================="
}

usage(){
    cat <<END
 Usage:

    `basename $0` <init|save|restore>
     `green 防火墙管理脚本`

 Description:
    `green init`    第一次初始化防火墙规则，白名单为空
    `green save`    导出防火墙规则及白名单ipset列表
    `green restore` 恢复防火墙规则及白名单ipset列表
    `green status`  查看防火墙状态规则

    `green add_port` 添加开放TCP端口 
    `green add_wip`  添加白名单IP
    `green del_port` 删除开放TCP端口 
    `green del_wip`  删除白名单IP
END
}

action="$1"
case "$action" in
    init)
        firewall_init
        ;;
    save)
        firewall_save
        ;;
    restore)
        firewall_restore
        ;;
    status)
        firewall_status
        ;;
    add_wip|add_port|del_wip|del_port)
        $action $2
        ;;
    *)
        usage
        ;;
esac


